### ISSUE TITLE
Pinch to zoom is laggy

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#1783]
**Affects versions :**
 - OS: Manjaro
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use
    gtk3 1:3.24.14+9+g429a6287e0-1 
    gtk2 2.24.32-2
 - Version of Xournal++: 1.1.0+dev 46a4dc82
 - Installation method: AUR

**Describe the bug**
Zooming is generally laggy

**Comment by Technius** [comment]
This is likely caused caused by the canvas widget having to resize on document changes. I'll see I can fix it in the upcoming viewport refactoring.

**Comment by coldspark29** [comment]
Will you maybe also be able to fix the weird shifting to the side when zooming in?

**Comment by Technius** [comment]
I'll look into it; the goal is to overhaul the current zoom/layout spaghetti code so that it's easier to fix these kinds of issues.

**Comment by chron-isch** [comment]
This should be fixed by #2435.

**Comment by Technius** [comment]
Has this lagginess been fixed?

**Comment by coldspark29** [comment]
Yes, it has become smoother. There is still room for improvement though. I think it is less of a lag, but more a sluggish rescaling

**Comment by coldspark29** [comment]
So #2718 is fixed and I thinkt he zooming is still laggy.

**Comment by ohthehugemanatee** [comment]
Still laggy when pinch-zooming out quickly on 1.1.0+dev, commit 8f83a043, libgtk 3.24.26 .

To reproduce:
1) create a document
2) pinch to zoom in
3) unpinch to zoom out, quickly

- Doesn't seem affected by drawigs on the page
- It is much worse on a PDF. 
- It ends at the right place
- You can continue the gesture after the lag
- Nothing is output in stdout/stderr
- it is as if it just dropped a lot of video frames in the zoom.

Guessing that this is because we re-render at a scale-appropriate resolution at each step of the zoom. If that's the case, we could do it like OSX Preview does it, instead: resize a the document at the current resolution, and re-render as an asynchronous step.

**Comment by maribox** [comment]
Still have the same problem as @ohthehugemanatee in 1.2.2+dev, commit [c5ddca9](https://github.com/xournalpp/xournalpp/commit/c5ddca935d23883288251a970ee1a16c27e02a5f)

**Comment by bhennion** [comment]
See #7081 for progress in this direction

**Comment by michelangelo4** [comment]
I have found some kind of workaround for #7175. Set environmental variable `GDK_BACKEND=x11`, that is `GDK_BACKEND=x11 xournalpp` to achieve the 100% KDE Plasma scaling. Unfortunately, from what I've read gtk3 does not support fractional scaling (but apparently gtk4 does) so scaling the application back up with `GDK_SCALE=1.5` while maintaining the better zooming performance it not possible since using `GDK_SCALE=2` is just too big. Maybe this will be a complete workaround with gtk4 then...

EDIT: If you want to rescale the buttons back to the 125% size (give or take), you'll have to rebuild xournalpp slightly different. After cloning, go to `src/core/gui/toolbarMenubar`, edit `ToolButton.ccp` and change `GTK_ICON_SIZE_LARGE_TOOLBAR` to `GTK_ICON_SIZE_DND` in the argument of function `gtk_image_new_from_icon_name`. If you have plugin buttons, edit `PluginToolButton.cpp` in the same folder and replace `GTK_ICON_SIZE_SMALL_TOOLBAR` with `GTK_ICON_SIZE_DND` in the argument of function `gtk_image_new_from_icon_name`. Additionally you'll have to replace `gtk_button_set_icon_name(GTK_BUTTON(btn), t->iconName.c_str());` with `gtk_button_set_child(GTK_BUTTON(btn), getNewToolIcon());` following the logic from `ToolButton.cpp` because otherwise it doesn't work. Then build as usual.

**Comment by bhennion** [comment]
I think  this can be closed, fix by a bunch of recent PRs
