### ISSUE TITLE
Pinch-to-zoom scrolls up

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#1843]
**Affects versions :**
 - OS: Manjaro
 - Desktop environment: Plasma X11
 - Which version of libgtk do you use: gtk3 1:3.24.17+18+gcdd4349bfe-1
 - Version of Xournal++: 1.1.0+dev 6790c973
 - Installation method: AUR

**Describe the bug**
When you use pinch-to-zoom it also scrolls up, since the recent update I made today. I am using the new input system. Was this maybe caused by the recent Ctrl+scroll fix?

**Comment by Technius** [comment]
> Was this maybe caused by the recent Ctrl+scroll fix?

This seems likely. This is why we need the viewport refactor, so something like this doesn't happen...

**Comment by Dolland** [comment]
> **Affects versions :**
> 
> * OS: Manjaro
> * Desktop environment: Plasma X11
> * Which version of libgtk do you use: gtk3 1:3.24.17+18+gcdd4349bfe-1
> * Version of Xournal++: 1.1.0+dev [6790c97](https://github.com/xournalpp/xournalpp/commit/6790c9737494d209b41f266217085372e77eae05)
> * Installation method: AUR
> 
> **Describe the bug**
> When you use pinch-to-zoom it also scrolls up, since the recent update I made today. I am using the new input system. Was this maybe caused by the recent Ctrl+scroll fix?

Yep, me too but i'm affected by this bug by long time

**Comment by Technius** [comment]
This is confirmed to be a regression in #1935 due to the ctrl+scroll mouse fix.

**Comment by inducer** [comment]
In #1935, I identified fea36863a9fc44bdb4cab67a7d65e65635696c7e as the culprit commit.

**Comment by inducer** [comment]
(and reverting it on top of master fixes the behavior)

**Comment by dcolli23** [comment]
Hi all, is there any update on this issue? I'm experiencing this issue on the following machine:

Ubuntu 18.04
Gnome 3.28.4
Xournalpp 1.0.16

I have some experience with C++ yet none with GTK but if this is something that just needs some elbow grease and a couple hours of time I'd be willing to take a crack at it. Just let me know!

**Comment by Febbe** [comment]
This is fixed in the current master/nightly

**Comment by coldspark29** [comment]
No the problem is back. It always comes back. Just like Herpes.

**Comment by coldspark29** [comment]
Well actually it is a new issue now. Ulrich’s two-finger scrolling is messed up. It used to work flawlessly and now it works more like a page up / page down motion. The algorithm has problems to distinguish between zooming and scrolling. Plus scrolling is way too fast.

**Comment by personalizedrefrigerator** [comment]
This should be fixed in the current master/nightly...

**Comment by Dolland** [comment]
> This should be fixed in the current master/nightly...

Yep, it seems solved on branch master, thanks a lot!

**Comment by coldspark29** [comment]
This was already fixed before. It was solved in exchange for a trembling effect when zooming. Which is less annoying but still not optimal.
