### ISSUE TITLE
SVG exporter hangs

### ISSUE THREAD

**Issue by PatrickMassot** [xournalpp/xournalpp#2076]
**Affects versions :**
 - OS: Ubuntu 20.04
 - (Linux only) Desktop environment: X11

`xournalpp --version` says `unkown option`. But the help menu says 1.1.0+dev based on March 30th, 23:20:17. I *think* I installed it from the GitHub release page.

**Describe the bug**
Export as SVG hangs forever, displaying a blank window with title "Exporter".

**To Reproduce**
1. Draw anything
2. Try to export as SVG

**Expected behavior**
Get an SVG file

**Screenshots of Problem**
![screencast](https://user-images.githubusercontent.com/14060883/84945571-b7742e80-b0e7-11ea-90bb-a9bc40450222.gif)

**Additional context**
`xournalpp -i test.svg test.xopp` does work (instantly).

**Comment by Technius** [comment]
Can you reproduce the bug with the [latest nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly)?

**Comment by PatrickMassot** [comment]
I didn't manage to try this build. 

When I try to use the fossa .deb, apt complains that libzip4 is not installed. When I try to install libzip4, it complains it exists in the database but is not available. 

When I try the AppImage, it says `** (com.github.xournalpp.xournalpp:327529): WARNING **: 01:13:02.039: [Crash Handler] Crashed with signal 11`. In particular it says it's 1am, so I won't try harder today.

**Comment by Technius** [comment]
> When I try to use the fossa .deb, apt complains that libzip4 is not installed. When I try to install libzip4, it complains it exists in the database but is not available.

Ugh, looks like Ubuntu changed the package name for some reason. I have fixed the issue and it will be available in tomorrow's nightly build. In the meantime, you could try installing from the PPA.

**Comment by PatrickMassot** [comment]
The nightly build is still broken on fosa. It now installs but trying to lauch `xournalpp` triggers `xournalpp: error while loading shared libraries: libzip.so.4: cannot open shared object file: No such file or directory`.
Indeed I only have `/usr/lib/x86_64-linux-gnu/libzip.so.5` (and trying to pretend this is version 4 doesn't work).

**Comment by Technius** [comment]
This is very strange. We build the focal package on a focal VM image, so it should be compiling and linking with `libzip5`. I'll open another issue; please try the PPA in the meantime.

**Comment by PatrickMassot** [comment]
I installed through the PPA. In particular, I can now use:
```bash
$ xournalpp --version
Xournal++ 1.1.0+dev 
└──libgtk: 3.24.18 
```
and the exporter bug is still there (and it still works from the command line). Also note that saving the file as .xopp first doesn't fix the issue.

**Comment by eppolito** [comment]
I also see this behavior in the PPA version.

Operating System: Pop!_OS 20.10
Kernel: Linux 5.8.0-7642-generic
Architecture: x86-64
