### ISSUE TITLE
Crashes on saving since a few days

### ISSUE THREAD

**Issue by amonpuschel** [xournalpp/xournalpp#2197]
**Affects versions :unstable, since a few days
 - OS:  ubuntu 20.04
 - (Linux only) Desktop environment: default gnome
 - Which version of libgtk do you use
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Version of Xournal++: Xournal++ 1.1.0+dev 
                                      └──libgtk: 3.24.20
 - Installation method: PPA

**Describe the bug**
Fresh install (after apt purge)
First start gives weird message regarding config-directory: Old directory ~/.xournalpp does not exist (because I never used an old version), but xournalpp tries to copy it to the new location (~/.config/com.github.xournalpp.xournalpp) but fails. See screenshot
![xournalpp-config](https://user-images.githubusercontent.com/52835386/91607288-f2120700-e973-11ea-926d-133d433721ed.png)

After drawing some lines, I tried so save the file. Xournalpp crashed with

`* Message: 21:05:59.836: Migrating configuration from /home/os/.xournalpp to /home/os/.config/com.github.xournalpp.xournalpp
** Message: 21:05:59.836: Migration failed: filesystem error: cannot copy: No such file or directory [/home/os/.xournalpp] [/home/os/.config/com.github.xournalpp.xournalpp]

** (com.github.xournalpp.xournalpp:270964): WARNING **: 21:05:59.873: Failed to load "colornames.ini" (/home/os/.config/com.github.xournalpp.xournalpp/colornames.ini): No such file or directory

** (com.github.xournalpp.xournalpp:270964): WARNING **: 21:05:59.878: configfile does not exist /home/os/.config/com.github.xournalpp.xournalpp/settings.xml

ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
** Message: 21:06:00.062: Using default latex template in /usr/bin/../share/xournalpp/resources/default_template.tex

(com.github.xournalpp.xournalpp:270964): Gtk-WARNING **: 21:06:00.132: Theme parsing error: <data>:1:22: Junk at end of value for font-family

** (com.github.xournalpp.xournalpp:270964): WARNING **: 21:10:02.254: [Crash Handler] Crashed with signal 11

** (com.github.xournalpp.xournalpp:270964): WARNING **: 21:10:02.254: [Crash Handler] Wrote crash log to: /home/os/.cache/com.github.xournalpp.xournalpp/errorlogs/errorlog.20200828-211002.log

** (com.github.xournalpp.xournalpp:270964): WARNING **: 21:10:02.280: Trying to emergency save the current open document…

** (com.github.xournalpp.xournalpp:270964): WARNING **: 21:10:02.281: Successfully saved document to "/home/os/.config/com.github.xournalpp.xournalpp/emergencysave.xopp"`

Second start brings a "should I restore screen":
![xournalpp-restore](https://user-images.githubusercontent.com/52835386/91607678-96944900-e974-11ea-95e1-b0f51180db6c.png)
Selecting "Restore file" results in a crash again:
`** (com.github.xournalpp.xournalpp:271655): WARNING **: 21:20:40.428: Failed to load "colornames.ini" (/home/os/.config/com.github.xournalpp.xournalpp/colornames.ini): No such file or directory

ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

(com.github.xournalpp.xournalpp:271655): Gtk-WARNING **: 21:20:40.778: Theme parsing error: <data>:1:22: Junk at end of value for font-family

** (com.github.xournalpp.xournalpp:271655): WARNING **: 21:21:32.076: [Crash Handler] Crashed with signal 11

** (com.github.xournalpp.xournalpp:271655): WARNING **: 21:21:32.076: [Crash Handler] Wrote crash log to: /home/os/.cache/com.github.xournalpp.xournalpp/errorlogs/errorlog.20200828-212132.log

** (com.github.xournalpp.xournalpp:271655): WARNING **: 21:21:32.099: Trying to emergency save the current open document…

** (com.github.xournalpp.xournalpp:271655): WARNING **: 21:21:32.100: Successfully saved document to "/home/os/.config/com.github.xournalpp.xournalpp/emergencysave.xopp"`

**Comment by rolandlo** [comment]
There have been some issues with the latest filesystem changes, but they have been fixed today. If you update Xournal++ tomorrow, it should work.

**Comment by Febbe** [comment]
Thank you for the report, I can reproduce this issue and have a short workaround for you, but in my case it only happens once:
Try to create the folder ~/.config/com.github.xournalpp.xournalpp/

**Comment by Febbe** [comment]
Fixed

**Comment by alphazyx** [comment]
> Fixed

version 1.0.6-0~202008272013~ubuntu20.04.1_amd64 still crash on saving. Moreover it cannot open any xopp file.

**Comment by rolandlo** [comment]
The PPA version is not yet updated to the current master, it seems. It will probably take one more day. If you checkout the current master, it should already been fixed.
