### ISSUE TITLE
Strange behavior when using a graphics tablet

### ISSUE THREAD

**Issue by Luke-101** [xournalpp/xournalpp#2436]
**Affects versions :**
 - OS: Windows 10
 - Which version of libgtk do you use: 3.24.23
 - Version of Xournal++: 1.0.19
 - Installation method: official release

**Describe the bug**
When I use the pen instead of the mouse to write the location of the writing is shifted above the cursor, the distance seems to be connected by the distance of the cursor from the top of the screen.
It also as this strange behavior in the GUI menus above the drawing section.

**To Reproduce**
1. Plug your drawing tablet (mine is Huion H640P)
2. Go to Preferences --> Input Device to check that is recognised
3. Select the pen
4. Start drawing

**Expected behavior**
The pen should write in the same position of the cursor even when using a drawing tablet, and the GUI should be high lited in correcly.

**Screenshots of Problem**
![xournal++ error](https://user-images.githubusercontent.com/53636779/99968201-2477a880-2d99-11eb-97d0-791d2519ffde.gif)
P.S. only the last line in the video was made by using my mouse

**Additional context**
I also tried to:
- restart the pc (obviously)
- change the drawing tablet setting to mouse mode and set in the Preferences --> Input Devices the drawing tablet as a mouse
- change the usb port of the drawing tablet
- check that the drivers for the drawing tablet were up to date

also any other software (paint, krita) works as expected.

**Comment by allenzhao** [comment]
I also have a similar situation. I have 3 displays (including the graphics tablet), one is set at a higher DPI (150%). When I set the dpi to 100% it seems to work fine. That's a temporary workaround.

**Comment by Luke-101** [comment]
Hello, thanks that work but as you mentioned is only a temporary workaround, so I will not close the issue.
Thanks again for the tip.

**Comment by Mir1001** [comment]
Same problem here (2 monitors and Watcom tablet, Win10)! The tablet pen is not working correctly, but the mouse is. I have tried different settings, restart the program, restart Watcom software and it didn't help. Only old school restarting the computer it helped (killing in the task manager didn't hepled). I can't identify when it stops working. Sometimes when I open a program it starts this strange behavior. The current suspects are: after sleeping mode, plugin and plug out a tablet, closing/open application, playing with settings,... Next time I will try "allenzhao" suggestion.

**Comment by LittleHuba** [comment]
This reminds me of a GTK bug some time ago that broke with different scales for multi-screen setups. Could you please switch to the nightly release 1.1.0+dev as it is built using a newer GTK version which might fix your problem.

**Comment by Luke-101** [comment]
Unfortunately I just try the nightly release but it doesn't fix the issue

**Comment by kleinesfilmroellchen** [comment]
On the most stable build this issue persists. Is there a bug tracker for GTK? This seems to be GTK-specific as the last stable Inkscape build which also runs on GTK has the exact same issue.

**Comment by LittleHuba** [comment]
> Is there a bug tracker for GTK?

https://gitlab.gnome.org/GNOME/gtk/-/issues

> Update: Hadn't tried the DPI workaround of @allenzhao but yes, that solves the issue temporarily. My particular setup is three monitors, one low-res 100% DPI, one 4K that is usually at 150% DPI, and the HD drawing tablet at 100% DPI. This issue really only affects GTK apps, other freeware (tried GIMP, paint.net, Krita, MS Whiteboard, Autodesk Sketchbook) works fine.

This is exactly the workaround for the bug I mentioned previously. Please link the issue you create in the tracker of GTK here, so we can keep informed on the progress.

**Comment by kleinesfilmroellchen** [comment]
[Here is the GTK issue I just created, I linked them here as well.](https://gitlab.gnome.org/GNOME/gtk/-/issues/3558)

**Comment by lb90** [comment]
Hi everyone! This issue has been fixed in the [1.1.0-hotfix.1](https://github.com/xournalpp/xournalpp/releases/tag/1.1.0-hotfix.1) release! Could you make a test to confirm?

**Comment by Luke-101** [comment]
Hello, so I have now a different Pc station so this problem didn't affect me for some time but I still have a Windows Pc so I tried to reproduce it.
Before updating I tried to set the windows screen to 150% and the version that I was in (1.0.20) still had this problem, then I updated and it was fixed.
Thanks for the great work.

P.S. I love the new icons in 1.1

**Comment by nianyu87** [comment]
I use a xppen deco fun tablet,  set the dpi to 100% is a good solution for my problem. If someone want a good cheap tablet for  Xournal++, I recommend this article: https://pctechtest.com/best-digital-writing-pads-for-online-teaching/
