### ISSUE TITLE
Adjustable sensitivity

### ISSUE THREAD

**Issue by pizdjuk** [xournalpp/xournalpp#2545]
**Is your feature request related to a problem? Please describe.**

I own the Iskn Repaper 2 device. The device is driven with some proprietary software, but it can be adjusted as an classical input tablet. The problem is, that the sensitivity is moved to a weak side. The dynamic range is big, but I need to set the pen style - "very thick" to use it comfortable.

The problem appears, when I want to draw figures/axes/etc. They are drawn very thick, in accordance to the adjustment. So I need to change the pen style every time.

So the feature request is simply to integrate an adjustment setting to sensitivity of a pressure.

**Describe the solution you'd like**

Possibility to adjust pressure-thickness of a line. O simply "sensitivity".

**Comment by Technius** [comment]
Related: #1361

**Comment by pizdjuk** [comment]
please add  "bug". From a view of a user it is clearly a bug.

**Comment by personalizedrefrigerator** [comment]
I think this has been fixed by PR #2622!

**Comment by pizdjuk** [comment]
It is better! Thnx!! But the problem remains, since a maximum multiplier of 4.0x is still too small. Why there is a limit? How about logarithmic curve?

**Comment by rolandlo** [comment]
What multiplier would you need approximately?

**Comment by pizdjuk** [comment]
10-20x, I think

**Comment by pizdjuk** [comment]
PDF with an example

**Comment by pizdjuk** [comment]
https://dropmefiles.com/VE8Gw

**Comment by rolandlo** [comment]
You can actually experiment with it by editing the value in the settings glade file. Under Linux it should be stored in `/usr/share/xournalpp/ui/settings.glade` and the line you need to modify is line 53 (property name `upper`):

```
  <object class="GtkAdjustment" id="adjustmentPressureMultiplier">
    <property name="lower">0.5</property>
    <property name="upper">4</property>
    <property name="value">1</property>
    <property name="step-increment">0.05</property>
    <property name="page-increment">0.5</property>
  </object>
```
Replace the 4 by 20 (or some other value) and see, how it works out.

**Comment by pizdjuk** [comment]
Thanks! I try it
