### ISSUE TITLE
Performance issues with scanned PDFs

### ISSUE THREAD

**Issue by Photon89** [xournalpp/xournalpp#2890]
**Affects versions :**
 - OS: Manjaro Linux
 - (Linux only) Desktop environment: X11 (Xfce)
 - Which version of libgtk do you use: 3.24.24
 - Version of Xournal++: 1.0.20-hotfix and 1.1.0+dev (slightly different behaviour in the two versions, see below)
 - Installation method: Repository package and AUR package (built from latest git)

**Describe the bug**
When opening some scanned PDF files with Xournal++, there are severe performance issues. It doesn't happen to all files but if it happens to a file, then it happens reproducibly. Strangely, some files have a very similar file size, page size and number of pages but one of them shows the issue and another one doesn't. The problematic files I am currently dealing with are around 3,5MB file size, 3 pages with page size 792 x 1056 pts.

My hardware specs are rather low which might be one of the roots of the problem: Thinkpad X200T (Intel Core2 Duo L9400, 8GB of RAM; SSD).

Version 1.0.20:

Xournal++ takes some seconds to initially load the file (not significantly longer than any PDF viewer). The first page is loaded, the other two pages not yet. When I try to annotate the file, after 1-2 strokes the CPU goes to 100%, Xournal++ becomes unresponsive and new strokes aren't shown. They are shown later if I give Xournal++ some time to "cool down". After a "cool down" I can again write a few strokes till the CPU goes to 100% and further strokes aren't shown.

However, if I scroll down such that all three pages are loaded, the performance issue doesn't appear, I can annotate the file (almost) without performance problems.

Version 1.1.0: 

Same problem as in version 1.0.20 (subjectively, a bit more severe, that is, longer loading times) but now it does *not* help to scroll down and load all pages. Even if all pages are loaded, the CPU goes to 100% after every 1-2 strokes.

**To Reproduce**
1. Open a scanned PDF file of around 3,5MB file size
2. Use the pen tool to annotate it

**Expected behavior**
There should be no freezes.

**Comment by Technius** [comment]
Do you also see high memory usage?

**Comment by Photon89** [comment]
Not exceedingly high, below 200MB. But it behaves interestingly: In idle the memory is at about 130MB, during a freeze it goes to 170MB, drops to 130MB again, rises again and drops again, around 3-4 iterations of memory increase during one single freeze. The memory usage graph resembles a sawtooth wave during a freeze.

**Comment by Photon89** [comment]
Do you need an example file? I cannot upload one publicly but I think nobody will complain, if I send it to one person privately, as the pupil's name is not visible.

**Comment by rolandlo** [comment]
Yes, please share one privately. You can contact me in [Gitter](https://gitter.im/xournalpp/xournalpp) chat.

**Comment by Photon89** [comment]
Done!

**Comment by rolandlo** [comment]
I can reproduce the issue on a faster machine (Intel® Core™ i7-8550U CPU @ 1.80GHz × 8 , 16 GB of RAM) as well. Looking at the sidebar reveals, that it takes roughly 13 seconds until all pages are loaded.

**Comment by rolandlo** [comment]
If I open the document in `evince` the loading time is comparable, but there I cannot even scroll through the domcument without large waiting times. Moreover I repeatedly get the following message in the terminal.
```
Entity: line 10: parser error : xmlParseCharRef: invalid xmlChar value 0
dc:format='application/pdf'><dc:title><rdf:Alt><rdf:li xml:lang='x-default'>&#0;
```

**Comment by Photon89** [comment]
Yes, Atril also gets quite sluggish with this file... I generated it from three jpeg files, 1,2MB-1,6MB each, using imagemagick.

**Comment by rolandlo** [comment]
After compressing the `pdf` using:
```
gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dDownsampleColorImages=true -dColorImageResolution=150 -dNOPAUSE  -dBATCH -sOutputFile=xournalpp-test_Compressed.pdf xournalpp-test.pdf
```
(without noticable image quality loss) the performance issue went away. The CPU never exceeded 60% any more. Other compression methods I tried didn't solve the performance issue fully. 
@Photon89 It's only a workaround, but maybe you could try it with other scanned pdfs to check whether this workaround works in mostly all cases.

**Comment by Photon89** [comment]
I'm running over the PDFs with the gs command from https://github.com/xournalpp/xournalpp/issues/2424#issuecomment-787073675 anyway to make the pen thickness suiting, so I'll just add the additional options!

Will report back asap.

**Comment by rolandlo** [comment]
On Windows it's even worse. Document load of the orginal pdf takes about 45 seconds (instead of 13 seconds on Linux). Adobe Acrobat has it loaded in less than a second.

**Comment by Photon89** [comment]
Black magic. :) 

I reworked my script generating the PDF files using your proposal, now the resulting file is just 657kB instead of 3,5MB without visible quality loss and the performance problem is mostly gone. Now, with version 1.1.0 the strokes are sometimes invisible during writing but appear within a second after starting such an "invisible" stroke (was around 10 seconds or more before) and the CPU is not on fire any more. Thanks for the proposal!

Don't know if the issue should be closed or stay open, for me the practical problem is solved!

**Comment by rolandlo** [comment]
Great that the practical problem is solved. Let us leave the issue open for the time being, since it would still be possible to improve Xournal++ with regards to this issue or point out the upstream source (Poppler or Cairo?), where the problem originates from.

**Comment by meiaihara06** [comment]
Can confirm.
the problem still exists
![image](https://user-images.githubusercontent.com/46371349/121878811-62322380-cd21-11eb-8c77-15ee1097fa09.png)

while highlighting : the app often freezes for two or three seconds (My pdf file is 274 page scanned with relatively large page sizes)
while scrolling , it just doesn't scroll , takes me directly to next page (so much lag)
while zooming : it's not as bad , but still not perfect

OS: Windows 10 LTSC (1809)
Processor :  Core i7-2620M
RAM: 8GB (xournal uses 200MB on this file)

while freezing CPU activity goes up to 20% and then drops down
i don't see any huge change in RAM usage (just 10-20MB)

i tried:
disabling input stabilization ,rotation snapping , "drawing outside the window" , pressure sensitivity , "clear cached page after loading "
decreasing Before and After pre load pages to just one
i should note on more zoom this is even worse
It freezes every 2 seconds for four to five seconds
 
i will try :
compressing pdf file , so I hope it works

I will give more info, if it helps.

**Comment by Rmano** [comment]
Just as an extra info: how big (in Mbytes, I mean) is the file? I often have to reduce the resolution of scanned PDF exams form my students to make `xournalpp` usable on them... 

Another problem for speed is when page size is not exactly the same. Transitions especially when zoomed between different sized pages complicate things.

**Comment by meiaihara06** [comment]
> Just as an extra info: how big (in Mbytes, I mean) is the file?

95MB

> I often have to reduce the resolution of scanned PDF exams

i tried to reduce size and resolution with ghostscript , but it ended in a total disaster (entire original pdf converted to a blank 1 page pdf)
i used this command in source directory 
`gswin64c.exe -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile=".\my pdf filename which has spaces in it.pdf" "Output.pdf" `
in powershell

> Another problem for speed is when page size is not exactly the same
in my case it seems pages are in same size

**Comment by meiaihara06** [comment]
update:

i compressed pdf file with this command in cmd :
`
gswin64c -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dDownsampleColorImages=true -dColorImageResolution=150 -dNOPAUSE  -dBATCH -sOutputFile=DorDonyaFarsiOptd.pdf DorDonyaFarsi.pdf
`

and it didn't decrease pdf size noticeably (about 1MB in total)
but the overall performance is much much better

so thanks  to @rolandlo for this command

**Comment by Technius** [comment]
> Another problem for speed is when page size is not exactly the same. Transitions especially when zoomed between different sized pages complicate things.

We could definitely improve this by borrowing an idea from internet browsers: keep showing the currently rendered buffer but scaled to the new zoom level, but render the new zoom level in the background and swap when done.

**Comment by miromarszal** [comment]
This performance issue kept me from using xournalpp for quite a long time until I found out about the `gs` compression workaround here. Would you mind mentioning it somewhere on the front page for the time being? I'm guessing many users could be affected and simply decide that the program is unstable.

**Comment by Rmano** [comment]
Hi all!

I have found that another source of slowdown is when the document has page sizes that are different (even a bit), and you use the "zoom to fit" option. So now I use a `pdfjam` trick to scale all the pages to the same size *and* the `gs` trick above:

```
pdfjam  --outfile tmp.pdf --paper a4paper original.pdf
gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 \
        -dPDFSETTINGS=/ebook \
        -dNOPAUSE -dQUIET -dBATCH \
        -sOutputFile=compact.pdf tmp.pdf
```

...and things are much better (YMMV, if the page sizes are very different, that will result in a very strange-looking PDF...)

**Comment by tattsan** [comment]
By adding ` -sPAPERSIZE=a4  -dFIXEDMEDIA -dPDFFitPage ` option to `gs`, you can do the same thing as `pdfjam`.

**Comment by l-acs** [comment]
Out of curiosity, has anyone experienced this issue with relatively small and uniform PDFs? The one I'm having trouble with is only about 1MB (and the ghostscript compression doesn't shrink the file size or noticeably change the performance). It has color images, though.
If it helps- I'm on KDE Wayland on a Thinkpad X1 Titanium.

PS: let me know if I should open another issue instead, but it seems the same topic as this one, which is why I thought I'd try commenting here first.
