### ISSUE TITLE
Stylus buttons dont activate the tool that they are assigned for

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#3176]
**Affects versions :**
 - OS: Windows
 - Which version of libgtk do you use:  3.24.29
 - Version of Xournal++:  1.1.0+dev git commit 99df9684
 - Installation method: Installed from zip from github.

**Describe the bug**
On my tablet stylus, I have button one set to the hand tool, and button 2 set to the eraser tool. When I click the buttons, the tools show up on screen under the stylus like they are active, but when I touch the stylus to the screen, they do not perform their function. Instead, they just drag along the screen following the stylus.

**To Reproduce**
1. Assign a tool to a stylus button
2. Attempt to use this tool and observe that it shows up but does not function.

**Expected behavior**
The tools on the stylus buttons should work as expected.

**Additional context**
The tools work if I manually select them from the toolbar and not the stylus buttons.
The stylus buttons work as expected on Linux.

**Comment by rolandlo** [comment]
Currently massive improvements for input handling on MS Windows are underway from the side of GTK+, see #2316.  There are also some [test builds](https://github.com/xournalpp/xournalpp/issues/2316#issuecomment-840558655) there and a description how to build from source. So keep an eye on the progress in that thread. Looks like things will eventually be as good as on Linux.

**Comment by rolandlo** [comment]
The patched GTK+ 3 has now been merged. You can copy the `libgdk-3-0.dll` and `libgtk-3-0.dll` into your [Xournal++ 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) installation as described [here](https://github.com/xournalpp/xournalpp/issues/2316#issuecomment-873435907). This may solve the issue.

**Comment by rolandlo** [comment]
The issue should be fixed in [Version 1.1.0-hotfix+1](https://github.com/xournalpp/xournalpp/releases/tag/1.1.0-hotfix.1). Please report if you experience otherwise.

**Comment by HifeFish** [comment]
I am experiencing precisely the behaviour described here on a cube mix plus tablet on Windows 10 with 
Xournal++ version 1.1.1
Git commit 4f113e94
Built on Feb 13 2022, 19:54:01
libgtk 3.24.31
Installed from the Windows zip installer from github.

**Comment by asimard1** [comment]
This issue still happens here. Windows Surface with Surface Pen...
