### ISSUE TITLE
Black window on macos monterey

### ISSUE THREAD

**Issue by ch41** [xournalpp/xournalpp#3517]
**Affects versions :**
 - OS: **macos monterey**
 - Which version of libgtk do you use: 3.0
 - Version of Xournal++: 1.10
 - Installation method: **homebrew**

**Describe the bug**
black window after app luanch .

**To Reproduce**
just launch the app.

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/8329204/139063517-4c5c874b-1347-41d3-9ff3-4ce910e690a7.png)

**Comment by kfxiaoxia** [comment]
Same issue for me.

**Comment by rolandlo** [comment]
@ch41 Unfortunately the terminal output don't show any messages which identify the problem. The messages with "negative dimension" also appear on Catalina and BigSur.

**Comment by rolandlo** [comment]
Looks like this is a Gtk issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/4342

**Comment by rolandlo** [comment]
The issue should be fixed when Gtk 3.24.31 is released, see https://gitlab.gnome.org/GNOME/gtk/-/issues/4395. Hopefully that won't take too long.

**Comment by jeudicode** [comment]
I updated my gtk version since in https://gitlab.gnome.org/GNOME/gtk/-/issues/4395 the issue was marked as solved two days ago. However, I'm still having the black screen problem with xournalapp, same output as @ch41.

**Comment by LittleHuba** [comment]
Being solved and being part of the release is not necessarily the same. Or are you building GTK and Xournal++ from source?

**Comment by pythonpeixun** [comment]
Intel cpu
not Being solved

**Comment by xandstapleton** [comment]
Can confirm problem persists with Mac Air 2017 (Intel), GTK3 ver 3.24.30_1 from Homebrew. Source compiled latest stable Xournal++. Also persists with nightly Xournal++.

**Comment by paxperscientiam** [comment]
Environment: macOS 12.0.1 (Monterey), M1 chip
Release: 1.1.0

Same problem when opening app. Same terminal output as @ch41 too.


<img width="866" alt="Screen Shot 2021-11-29 at 6 16 07 PM" src="https://user-images.githubusercontent.com/7539871/143957748-765ffc67-d061-438d-a162-2de1bd02fdda.png">

**Comment by martinescardo** [comment]
I still get a black screen with gtk+3 3.24.30_1, with xournal-plus-plus installed with brew. Running on a MacBook Air with m1 chip, Monterey. Used to work with previous version of MacOS.

**Comment by alt-coder** [comment]
I did a lazy Workaround to fix this
1. Build the Xournalpp using home brew from the instruction [here](https://github.com/xournalpp/xournalpp/blob/master/readme/MacBuild.md)
this will generate Xournal binary
2. Download the Xournal++.app from the release page
3. Go to Xournal++.app/Contents/MacOS/ and replace the generated file here
![image](https://user-images.githubusercontent.com/84824354/146768557-4e2025ac-46a9-4584-b752-844057ad24aa.png)
The actual problem was with gtk only and fixed after update

**Comment by rolandlo** [comment]
GTK+ 3.24.31 has now been released (on Dec 20). It will probably take a couple of weeks until we have it in [gtk-osx](https://gitlab.gnome.org/GNOME/gtk-osx/). After that we will have to recompile GTK on MacOS and replace the blob we use in the Azure Pipelines. So the problem will be fixed in about one month.

**Comment by 2xmax** [comment]
@alt-coder Your approach only worked when I made a script like this:

```
cat /Applications/Xournal++.app/Contents/MacOS/xournalpp-bin
#!/bin/zsh

cd <the build folder>
./xournalpp
```
seems like a working directory issue. Without the fix, I still had a black window.

**Comment by rolandlo** [comment]
Can someone (who has MacOS Monterey installed) check if the build using the new Gtk blob from [this PR](https://github.com/xournalpp/xournalpp/pull/3759#issuecomment-1026212658) runs fine on MacOS Monterey? You will currently have to replace one line in the launcher script as described [here](https://github.com/xournalpp/xournalpp/pull/3759#issuecomment-1026241665), but that shouldn't be hard.

**Comment by anbaccar** [comment]
@rolandlo I can confirm it works with the line change. Without it the program opens/bounces briefly before closing.

However, the latest build is incredibly laggy with all input sources (mouse, stylus, etc.), specifically the delay between providing the input from the stylus being reflected in the program and lines not appearing smoothly.

I've never used the software on macOS prior to the GTK issue (I primarily use Ubuntu) so I can't compare apples to apples, and I'm not sure if this is something that will be resolved in the next official release, but the performance of the macOS build compared to the Ubuntu one I currently have installed is stark. I can provide demo comparing the two if necessary.

**Comment by martinescardo** [comment]
It also works for me with the line change. Thanks.

**Comment by rolandlo** [comment]
> @rolandlo I can confirm it works with the line change. Without it the program opens/bounces briefly before closing.
> 
Thanks for testing. 

> However, the latest build is incredibly laggy with all input sources (mouse, stylus, etc.), specifically the delay between providing the input from the stylus being reflected in the program and lines not appearing smoothly.
> 
> I've never used the software on macOS prior to the GTK issue (I primarily use Ubuntu) so I can't compare apples to apples, and I'm not sure if this is something that will be resolved in the next official release, but the performance of the macOS build compared to the Ubuntu one I currently have installed is stark. I can provide a demo comparing the two if necessary.

Unfortunately that is mostly expected and comes from the poor performance of the graphics library Cairo on MacOS (that is also felt in other Gtk apps like GIMP). Some Gtk devs are working on it (see [this issue](https://gitlab.gnome.org/GNOME/gtk/-/issues/3714#note_1371264)) and some improvements can be expected in the future, but Cairo based drawing apps will probably never be nearly as smooth on MacOS like on Linux or Windows. See also #2302 and this [GIMP issue](https://gitlab.gnome.org/GNOME/gimp/-/issues/7690)

**Comment by rolandlo** [comment]
> It also works for me with the line change. Thanks.

Thanks for testing.

**Comment by rolandlo** [comment]
Now the [latest installer](https://github.com/xournalpp/xournalpp/pull/3759#issuecomment-1027391808) should work (on MacOS) without any line change by the user. It uses the same Gtk blob which it now fetches from the official repository in the build phase. Could you please test once more on MacOS Monterey @martinescardo and @anbaccar ?

**Comment by anbaccar** [comment]
@rolandlo I can confirm it works without any modifications.

**Comment by jeudicode** [comment]
I can also confirm the installer works without modifications.

**Comment by martinescardo** [comment]
It works for me too.

**Comment by martinescardo** [comment]
It is great that it works now. Thanks for your efforts.
It is a pity, though, that the precision of xournalpp is very low on a mac, compared to linux. 
I was looking forward to record lectures using a mac, but in the end I had to go back to an old linux machine, with which xournalpp produces higher-quality results with a much faster response and lower cpu usage, saving cycles for OBS.

**Comment by rolandlo** [comment]
This is fixed in the [nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly), which uses Gtk 3.24.30 with (offical) patches for MacOS Monterey. So I am closing the issue.

**Comment by sorchiazzo** [comment]
Dears,

 I am a newbie about homebrew and all this world, have been for many years a simple MacOs user. Last year I installed on my x86 a software called "homebank" and managed to do it with homebrew after a couple of try.
I found this software extremely useful for my financial control.
Now I have switched to a newer MacBook Pro with Monterey (ARM chip) and I have been struggling to have it running. Homebrew installation worked out ok, but then I hit the same issue of the black screen as described above. How do I check which Gtk version has been installed? How can I update it?
<img width="1457" alt="Screenshot 2022-04-02 at 9 59 57 PM" src="https://user-images.githubusercontent.com/102878872/161409374-6a529695-ea34-41de-823b-ef285d3f710e.png">

Thanks in advance
