### ISSUE TITLE
Won't Install on Ubuntu 25.10

### ISSUE THREAD

**Issue by EVAditya** [xournalpp/xournalpp#6828]
### Operating System

Linux

### (Linux only) Distribution

Ubuntu

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

Wayland

### Installation Method

Official Release

### Xournal++ Version

1.2.7

### libgtk Version

3

### Bug Description

Tried to install using
sudo apt install xournalpp

It gave this error message
Error: Unable to satisfy dependencies. Reached two conflicting decisions:
   1. xournalpp:amd64=2:1.2.8+dev-202511171541~ubuntu25.10.1 is selected for install
   2. xournalpp:amd64=2:1.2.8+dev-202511171541~ubuntu25.10.1 Depends libxml2 (>= 2.0.0)
      but none of the choices are installable:
      [no choices]

But libxml2 is installed.

### Expected Behaviour

Should have installed without trouble

### Steps to Reproduce

1. sudo apt install xournalpp

### Additional Context

:~$ sudo apt install xournalpp
Solving dependencies... Error!  
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

Unsatisfied dependencies:
 xournalpp : Depends: libgtksourceview-4-0 (>= 3.16.1) but it is not going to be installed
             Depends: liblua5.3-0 but it is not going to be installed
             Depends: libportaudio2 (>= 19+svn20101113) but it is not going to be installed
             Depends: libportaudiocpp0 (>= 12) but it is not going to be installed
             Depends: libxml2 (>= 2.0.0) but it is not installable
             Depends: qpdf (>= 10.6) but it is not going to be installed
Error: Unable to satisfy dependencies. Reached two conflicting decisions:
   1. xournalpp:amd64=2:1.2.8+dev-202511171541~ubuntu25.10.1 is selected for install
   2. xournalpp:amd64=2:1.2.8+dev-202511171541~ubuntu25.10.1 Depends libxml2 (>= 2.0.0)
      but none of the choices are installable:
      [no choices]

**Comment by bhennion** [comment]
This is a bug in Ubuntu packaging (not our doing), which has already been solved by the distribution (libxml2 was renamed libxml2-16 for some reason). Just try again and it should work.

**Comment by thoschi** [comment]
This is still a problem in 01/2026 for packages from the Ubuntu repo.

If 25.10 renames a package (for whatever reason), the corresponding dependencies should be updated, should'nt it?

**Comment by thoschi** [comment]
An upgrade to 1.3.3 still fails for the same reason - now libxml-16 is in the control file, but libxml2 is still there so it still fails.

Here my actual workaround (hoping, that the repo problem is solved some day soon):
```
mkdir -p /tmp/repxpp && cd /tmp/repxpp                    # create temporary directory
apt-get download xournalpp                                # download deb file
dpkg-deb -R xournalpp_*.deb work                          # extract deb
sed -i "s/, libxml2 (>= 2.0.0)//g;" work/DEBIAN/control   # remove libxml2 from control file
dpkg-deb -b work xournalpp_changed.deb                    # re-pack deb file
sudo dpkg -i xournalpp_changed.deb                        # install changed deb file
# cd ~ && rm -rf /tmp/repxpp                              # uncomment to remove temp dir
```
If you like, avoid automatic "repair" of the package (but dont forget you did):

`sudo apt-mark unhold xournalpp`

Another and probably better workaround is to use equivs to set up a dummy libxml2 package that relies von libxml2-16:

```
sudo apt install -y equivs       # install equivs
equivs-control libxml2           # create template

# write the template file
cat > libxml2 <<EOF
Package: libxml2
Version: 1.0
Architecture: all
Provides: libxml2
Depends: libxml2-16
Description: compatibility package mapping libxml2 to libxml2-16
EOF

equivs-build libxml2              # build the dummy package
sudo dpkg -i libxml2_1.0_all.deb  # install dummy package
```
Afterwards you can install xournalpp as usual:

`apt install --reinstall xournalpp`

Though best of all would just be to remove the libxml2-dependancy from the repos with the renamed package.

**Comment by bhennion** [comment]
I'm a bit confused here. Are you try to install the .deb we build for Ubuntu 24.04 LTS on Ubuntu 25.10?

**Comment by thoschi** [comment]
I read the installation instructions at https://xournalpp.github.io/installation/linux/
There it mentions the apandada1-PPA for Ubuntu based installations

If you try to use the ppa (to get a recent version of Xournal++) or if you upgrade with this PPA from 24.04, install fails on Ubuntu 25.10 - that's what this issue is about.

It fails as far as I understood because libxml2 has been renamed to libxml2-16. This was done as far as I read due to breaking API changes in libxml2 libraries.

So far just changing the dependencies or creating a dummy libxml2-package seems to work fine - I have no issues with xournal++ so far. But it would probably be better to either change the dependency inside the repo to make the installation work in Ubuntu 25.10 - or inform about this issue on the install page.

**Comment by domenicozambella** [comment]
On a fresh installation of kubuntu 25.10 

    sudo dpkg -i libxml2_1.0_all.deb

produces the following error message (and xournalpp does not install)

    dpkg: dependency problems prevent configuration of libxml2:
    zlib1g:amd64 (1:1.3.dfsg+really1.3.1-1ubuntu2) breaks libxml2 (<< 2.7.6.dfsg-2) and is installed.

**Comment by j-lakeman** [comment]
Just ran into this on Ubuntu 26.04 LTS. Pls reopen.

**Comment by rolandlo** [comment]
> Just ran into this on Ubuntu 26.04 LTS. Pls reopen.

Try the latest nightly or the PPA.

**Comment by j-lakeman** [comment]
Just tried the PPA - same result. I'd need a stable solution therefore nightly isn’t really an option.

**Comment by bhennion** [comment]
> Just tried the PPA - same result. I'd need a stable solution therefore nightly isn’t really an option.

So what version are you trying to install? From what server?
The CPack dependency list was updated in v1.3.6, to match the changes brought by Ubuntu 26.04.

**Comment by bhennion** [comment]
Closing for lack of infoClosing for lack of info
