### ISSUE TITLE
make fails on Debian Stretch

### ISSUE THREAD

**Issue by agtig** [xournalpp/xournalpp#992]
When following the build instructions and installing the dependencies, the cmake works fine, but the make command fails with the following
```
xournalpp/src/control/tools/EditSelectionContents.cpp: In member function ‘void EditSelectionContents::finalizeSelection(double, double, double, double, bool, Layer*, PageRef, XojPageView*, UndoRedoHandler*)’:
/home/sand/Downloads/xournal/xournalpp/src/control/tools/EditSelectionContents.cpp:406:35: error: call of overloaded ‘abs(double&)’ is ambiguous
  bool rotate = (abs(this->rotation) > __DBL_EPSILON__);
```
And following this is many references to overloaded 'abs(double&)'

I don't know how to solve it easily?

**Comment by peetCreative** [comment]
Can you try to build it from this fork? Probably sth like this happens because of this: 
https://stackoverflow.com/questions/1374037/ambiguous-overload-call-to-absdouble

**Comment by agtig** [comment]
It doesn't seem to change anything. What kind of information can I provide that is helpful?
I git clone the repository (this time the fork), create a build directory, enters the build directory and run 'cmake ..'

I get the following output:

`[ 32%] Building CXX object src/CMakeFiles/xournalpp-core.dir/control/tools/EditSelectionContents.cpp.o
/home/sand/Downloads/xournal/fork/xournalpp/src/control/tools/EditSelectionContents.cpp: In member function ‘void EditSelectionContents::finalizeSelection(double, double, double, double, bool, Layer*, PageRef, XojPageView*, UndoRedoHandler*)’:
/home/sand/Downloads/xournal/fork/xournalpp/src/control/tools/EditSelectionContents.cpp:406:35: error: call of overloaded ‘abs(double&)’ is ambiguous
  bool rotate = (abs(this->rotation) > __DBL_EPSILON__);
                                   ^
In file included from /usr/include/c++/6/cstdlib:75:0,
                 from /usr/include/c++/6/ext/string_conversions.h:41,
                 from /usr/include/c++/6/bits/basic_string.h:5417,
                 from /usr/include/c++/6/string:52,
                 from /home/sand/Downloads/xournal/fork/xournalpp/src/util/XournalType.h:23,
                 from /home/sand/Downloads/xournal/fork/xournalpp/src/control/ToolEnums.h:14,
                 from /home/sand/Downloads/xournal/fork/xournalpp/src/control/ToolBase.h:15,
                 from /home/sand/Downloads/xournal/fork/xournalpp/src/control/Tool.h:14,
                 from /home/sand/Downloads/xournal/fork/xournalpp/src/control/tools/EditSelectionContents.h:16,
                 from /home/sand/Downloads/xournal/fork/xournalpp/src/control/tools/EditSelectionContents.cpp:1:
/usr/include/stdlib.h:735:12: note: candidate: int abs(int)
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
            ^~~
`

**Comment by agtig** [comment]
The reason for filing this issue, is that I couldn't get the ppa to work on debian. I don't remember what the issue was, but I think it was https and pgp related, and then 
> apt-get update 

would just hang. This should maybe go somewhere else, but just to explain why I ended up trying to build it myself.

**Comment by LittleHuba** [comment]
See #959 for an explanation why PPAs on Debian are a bad idea. 

We have to use `fabs()` instead of `abs()` this fixes those bugs as it removes the ambiguous implicit cast.

**Comment by LittleHuba** [comment]
This should be solved now as we switched to `cmath`. Could you verify @agtig?

**Comment by agtig** [comment]
@LittleHuba: Still fails. Seems that there are more references to abs()? Here's the output:
`[ 13%] Building CXX object src/CMakeFiles/xournalpp-core.dir/control/tools/EditSelection.cpp.o
/home/sand/git/xournalpp/src/control/tools/EditSelection.cpp: In member function ‘void EditSelection::snapRotation()’:
/home/sand/git/xournalpp/src/control/tools/EditSelection.cpp:752:44: error: call of overloaded ‘abs(double)’ is ambiguous
   if (abs(this->rotation - ROTATION_LOCK[i]) < epsilon)
                                            ^
In file included from /usr/include/c++/6/cstdlib:75:0,
                 from /usr/include/c++/6/ext/string_conversions.h:41,
                 from /usr/include/c++/6/bits/basic_string.h:5417,
                 from /usr/include/c++/6/string:52,
                 from /home/sand/git/xournalpp/src/util/XournalType.h:23,
                 from /home/sand/git/xournalpp/src/control/ToolEnums.h:14,
                 from /home/sand/git/xournalpp/src/control/ToolBase.h:15,
                 from /home/sand/git/xournalpp/src/control/Tool.h:14,
                 from /home/sand/git/xournalpp/src/control/tools/EditSelection.h:17,
                 from /home/sand/git/xournalpp/src/control/tools/EditSelection.cpp:1:
/usr/include/stdlib.h:735:12: note: candidate: int abs(int)
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
            ^~~
In file included from /usr/include/c++/6/ext/string_conversions.h:41:0,
                 from /usr/include/c++/6/bits/basic_string.h:5417,
                 from /usr/include/c++/6/string:52,
                 from /home/sand/git/xournalpp/src/util/XournalType.h:23,
                 from /home/sand/git/xournalpp/src/control/ToolEnums.h:14,
                 from /home/sand/git/xournalpp/src/control/ToolBase.h:15,
                 from /home/sand/git/xournalpp/src/control/Tool.h:14,
                 from /home/sand/git/xournalpp/src/control/tools/EditSelection.h:17,
                 from /home/sand/git/xournalpp/src/control/tools/EditSelection.cpp:1:
/usr/include/c++/6/cstdlib:185:3: note: candidate: __int128 std::abs(__int128)
   abs(__GLIBCXX_TYPE_INT_N_0 __x) { return __x >= 0 ? __x : -__x; }
   ^~~
/usr/include/c++/6/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
/usr/include/c++/6/cstdlib:172:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
/home/sand/git/xournalpp/src/control/tools/EditSelection.cpp: In member function ‘void EditSelection::paint(cairo_t*, double)’:
/home/sand/git/xournalpp/src/control/tools/EditSelection.cpp:771:24: error: call of overloaded ‘abs(double&)’ is ambiguous
  if (abs(this->rotation) > __DBL_EPSILON__)
                        ^
In file included from /usr/include/c++/6/cstdlib:75:0,
                 from /usr/include/c++/6/ext/string_conversions.h:41,
                 from /usr/include/c++/6/bits/basic_string.h:5417,
                 from /usr/include/c++/6/string:52,
                 from /home/sand/git/xournalpp/src/util/XournalType.h:23,
                 from /home/sand/git/xournalpp/src/control/ToolEnums.h:14,
                 from /home/sand/git/xournalpp/src/control/ToolBase.h:15,
                 from /home/sand/git/xournalpp/src/control/Tool.h:14,
                 from /home/sand/git/xournalpp/src/control/tools/EditSelection.h:17,
                 from /home/sand/git/xournalpp/src/control/tools/EditSelection.cpp:1:
/usr/include/stdlib.h:735:12: note: candidate: int abs(int)
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
            ^~~
In file included from /usr/include/c++/6/ext/string_conversions.h:41:0,
                 from /usr/include/c++/6/bits/basic_string.h:5417,
                 from /usr/include/c++/6/string:52,
                 from /home/sand/git/xournalpp/src/util/XournalType.h:23,
                 from /home/sand/git/xournalpp/src/control/ToolEnums.h:14,
                 from /home/sand/git/xournalpp/src/control/ToolBase.h:15,
                 from /home/sand/git/xournalpp/src/control/Tool.h:14,
                 from /home/sand/git/xournalpp/src/control/tools/EditSelection.h:17,
                 from /home/sand/git/xournalpp/src/control/tools/EditSelection.cpp:1:
/usr/include/c++/6/cstdlib:185:3: note: candidate: __int128 std::abs(__int128)
   abs(__GLIBCXX_TYPE_INT_N_0 __x) { return __x >= 0 ? __x : -__x; }
   ^~~
/usr/include/c++/6/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
/usr/include/c++/6/cstdlib:172:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
src/CMakeFiles/xournalpp-core.dir/build.make:1358: recipe for target 'src/CMakeFiles/xournalpp-core.dir/control/tools/EditSelection.cpp.o' failed
make[2]: *** [src/CMakeFiles/xournalpp-core.dir/control/tools/EditSelection.cpp.o] Error 1
CMakeFiles/Makefile2:212: recipe for target 'src/CMakeFiles/xournalpp-core.dir/all' failed
make[1]: *** [src/CMakeFiles/xournalpp-core.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by agtig** [comment]
@LittleHuba I did a new git clone, and ran the build commands on that.

**Comment by LittleHuba** [comment]
I'll take a look and search for the missed references.

**Comment by agtig** [comment]
@LittleHuba Just to confirm. Did a `git pull` and tried to build again. This time without any errors...
